[meta]
    seed = 0
    quant_bits = 8          # Only support 8 or 16 now.
    batch_size = 32
    calib_steps = 32         # The minimum value for calib_steps is 8.
    model_version = 1
    target = "esp32p4"


[models_test]
    [models_test.picodet]
        input_shape = [1, 3, 224, 224]
        onnx_model_path = "picodet_xs_224_mod_chns_relu_rep_sim.onnx"
        export_path = ""
        export_name_prefix = "picodet_xs_224_mod_chns_relu_rep_sim"

    [models_test.mobilenet_v2]
        input_shape = [1, 3, 224, 224]
        onnx_model_path = "mobilenet_v2.onnx"
        export_path = ""
        export_name_prefix = "mobilenet_v2"
